/**
 * @file Recipes for Minecraft's classic dyes.
 */

ServerEvents.recipes(event => {
  // CLASSIC DYE CREATION
  event.recipes.kubejs.shapeless('minecraft:classic_white_dye', [
    '#forge:dyes/white',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_white_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_light_gray_dye', [
    '#forge:dyes/light_gray',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_light_gray_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_dark_gray_dye', [
    '#forge:dyes/gray',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_dark_gray_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_red_dye', [
    '#forge:dyes/red',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_red_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_orange_dye', [
    '#forge:dyes/orange',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_orange_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_yellow_dye', [
    '#forge:dyes/yellow',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_yellow_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_chartreuse_dye', [
    '#forge:dyes/lime',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_chartreuse_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_green_dye', [
    '#forge:dyes/green',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_green_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_spring_green_dye', [
    '#forge:dyes/lime',
    '#forge:dyes/cyan',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_spring_green_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_cyan_dye', [
    '#forge:dyes/cyan',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_cyan_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_capri_dye', [
    '#forge:dyes/light_blue',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_capri_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_ultramarine_dye', [
    '#forge:dyes/blue',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_ultramarine_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_violet_dye', [
    '#forge:dyes/purple',
    '#forge:dyes/blue',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_violet_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_purple_dye', [
    '#forge:dyes/purple',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_purple_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_magenta_dye', [
    '#forge:dyes/magenta',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_magenta_dye')
  event.recipes.kubejs.shapeless('minecraft:classic_rose_dye', [
    '#forge:dyes/magenta',
    '#forge:dyes/red',
    'minecraft:clock'
  ]).keepIngredient('minecraft:clock')
    .id('minecraft:classic_rose_dye')
  // WOOL DYEING
  /*
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
  */
  event.recipes.kubejs.shapeless('minecraft:classic_white_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_white_dye'
  ]).id('minecraft:dye_classic_white_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_light_gray_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_light_gray_dye'
  ]).id('minecraft:classic_light_gray_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_dark_gray_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_dark_gray_dye'
  ]).id('minecraft:dye_classic_dark_gray_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_red_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_red_dye'
  ]).id('minecraft:dye_classic_red_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_orange_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_orange_dye'
  ]).id('minecraft:dye_classic_orange_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_yellow_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool'
    ],
    'minecraft:classic_yellow_dye'
  ]).id('minecraft:dye_classic_yellow_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_chartreuse_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_chartreuse_dye'
  ]).id('minecraft:dye_classic_chartreuse_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_green_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_green_dye'
  ]).id('minecraft:dye_classic_green_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_spring_green_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_spring_green_dye'
  ]).id('minecraft:dye_classic_spring_green_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_cyan_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_cyan_dye'
  ]).id('minecraft:dye_classic_cyan_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_capri_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_capri_dye'
  ]).id('minecraft:dye_classic_capri_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_ultramarine_wool', [
    [
      'minecraft:black_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_ultramarine_dye'
  ]).id('minecraft:dye_classic_ultramarine_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_violet_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_violet_dye'
  ]).id('minecraft:dye_classic_violet_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_purple_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_purple_dye'
  ]).id('minecraft:dye_classic_purple_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_magenta_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_magenta_dye'
  ]).id('minecraft:dye_classic_magenta_wool')
  event.recipes.kubejs.shapeless('minecraft:classic_rose_wool', [
    [
      'minecraft:black_wool',
      'minecraft:blue_wool',
      'minecraft:brown_wool',
      'minecraft:cyan_wool',
      'minecraft:gray_wool',
      'minecraft:green_wool',
      'minecraft:light_blue_wool',
      'minecraft:light_gray_wool',
      'minecraft:lime_wool',
      'minecraft:magenta_wool',
      'minecraft:orange_wool',
      'minecraft:pink_wool',
      'minecraft:purple_wool',
      'minecraft:red_wool',
      'minecraft:white_wool',
      'minecraft:yellow_wool'
    ],
    'minecraft:classic_rose_dye'
  ]).id('minecraft:dye_classic_rose_wool')
})